apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto1-app
  labels:
    app: projeto1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto1-app
  template:
    metadata:
      labels:
        app: projeto1-app
    spec:
      containers:
        - name: projeto1-app
          image: projeto1-app:latest # <--- Esta imagem precisa ser construída localmente ou puxada de um registry
          ports:
            - containerPort: 80 # Porta que o container PHP/Apache estará escutando
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"