apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Nome do serviço para o MySQL
  labels:
    app: mysql
spec:
  selector:
    app: mysql # Seleciona os pods do Deployment 'mysql-deployment'
  ports:
    - protocol: TCP
      port: 3306 # Porta que o serviço irá expor
      targetPort: 3306 # Porta do container do MySQL
  clusterIP: None # headless service para que a aplicação possa resolver os pods diretamente