apiVersion: v1
kind: Service
metadata:
  name: projeto1-service # Nome do serviço para a aplicação
  labels:
    app: projeto1-app
spec:
  selector:
    app: projeto1-app # Seleciona os pods do Deployment 'projeto1-app'
  ports:
    - protocol: TCP
      port: 80 # Porta que o serviço irá expor
      targetPort: 80 # Porta do container que o serviço irá redirecionar
  type: LoadBalancer # Tipo de serviço. Para Minikube, isso normalmente expõe externamente.