FROM php:7.4-apache

# Install dependencies
WORKDIR /var/www/html
COPY index.php /var/www/html/
COPY conections.php /var/www/html/

RUN apt-get update && apt-get install -y \
  libpng-dev \
  libjpeg62-turbo-dev \
  libfreetype6-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install zip \
  && docker-php-ext-install mysqli

EXPOSE 80